important_class_dict = {
    "A2CH": ["LA cavity", "LV cavity", "LV wall", "MV posterior leaflet", "MV anterior leaflet",],
    "A3CH": [
        "LA cavity",
        "LV cavity",
        "Aorta",
        "LV wall",
        "Aortic wall",
        "MV anterior leaflet",
        "MV posterior leaflet",
        "NCC or LCC",
        "RCC",
    ],
    "A4CH": [
        "LA cavity",
        "LV cavity",
        "RA cavity",
        "RV cavity",
        "LV wall",
        "RV free wall",
        "IAS (Inter artrial septum)",
        "MV anterior leaflet",
        "MV posterior leaflet",
        "TV anterior leaflet",
        "TV septal leaflet",
    ],
    "PLAX": [
        "Aorta",
        "IVS (Inter ventricular septum)",
        "LA cavity",
        "LV cavity",
        "RV cavity",
        "LV posterior wall",
        "Aortic wall",
        # "Descending aorta",
        "MV anterior leaflet",
        "MV posterior leaflet",
        "RCC",
        "NCC or LCC",
    ],
    "PSAX apex": ["RV cavity", "LV wall", "LV cavity", "RV free wall"],
    "PSAX AV level": [
        "Aortic annulus",
        "LA cavity",
        "LCC",
        "Main Pulmonary artery",
        "IAS (Inter artrial septum)",
        "NCC",
        "RV cavity",
        "RV free wall",
        "RCC",
        "RA cavity",
        "TV anterior or septal leaflet",
    ],
    "PSAX basal": [
        "RV cavity",
        "LV wall",
        "LV cavity",
        "MV anterior leaflet",
        "MV posterior leaflet",
        "Mitral orifice",
    ],
    "PSAX mid": ["RV cavity", "LV wall", "LV cavity", "Anterolateral PM", "Posteromedial PM", "RV free wall",],
    "Subcostal": [
        "LV cavity",
        "LV wall",
        "RV cavity",
        "RA cavity",
        "RV free wall",
        "IAS (Inter artrial septum)",
        "LA cavity",
    ],
}
